# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - five_dof_robot_arm_controller

  five_dof_robot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Revolute 18
      - Revolute 19
      - Revolute 35
      - Revolute 34
      - Revolute 21
    action_ns: follow_joint_trajectory
    default: true